### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "Admin",
  "email": "admin@test.com",
  "password": "password",
  "password_confirmation": "password",
  "phone_number": "3456789012"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password"
}
