### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "Admin",
  "email": "admin@test.com",
  "password": "password",
  "password_confirmation": "password",
  "phone_number": "3456789012"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password"
}

### Property Update
PATCH http://localhost:3000/properties/13.json
Content-Type: application/json

{
  "listed_price": 2000000
}


### Tour Test

GET http://localhost:3000/tours.json 

### Image Test

POST http://localhost:3000/images.json
Content-Type: application/json

{
  "property_id": 18,
  "image_url": "https://upload.wikimedia.org/wikipedia/commons/2/22/HK_Bank_of_China_Tower_View.jpg"
}

### Favorite Delete Test

DELETE http://localhost:3000/favorites/1.json

### API TEST

GET http://localhost:3000/properties/1/data.json

